[tool.dagster]
module_name = "company"

[tool.mypy]
incremental = true
ignore_missing_imports = true
no_implicit_optional = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_equality = true
plugins = ["sqlalchemy.ext.mypy.plugin"]

[tool.black]
target-version = ["py310"]
line-length = 108

[tool.ruff]
select = ["I", "E", "F", "T", "UP", "B", "INP"]
target-version = "py310"
line-length = 108

[tool.ruff.per-file-ignores]
"data-warehouse/bin/generate_holiday_calendar.py" = ["INP001"]
