repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies:
          - dbt-core>=1.8.0
          - dbt-snowflake>=1.7.0
          - sqlfluff-templater-dbt>=3.0.0
      - id: sqlfluff-fix
        additional_dependencies:
          - dbt-core>=1.8.0
          - dbt-snowflake>=1.7.0
          - sqlfluff-templater-dbt>=3.0.0

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]

  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.2
    hooks:
      - id: check-model-has-description
      - id: check-model-has-tests
        args: [--test-cnt, "1"]
